[package]
name = "rust-websockets-tokio-study"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
